version: "3.8"

services:
  app:
    container_name: nextjs-curso-dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next  # Volume anônimo para evitar cache no host
    # user: "node"
    environment:
      - NODE_ENV=development
