version: "3.8"

services:
  app:
    container_name: nextjs-curso-dev
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      # - /app/node_modules
      # - /app/.next  # Volume anônimo para evitar cache no hosts
    user: "node"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_DISABLE_FILE_SYSTEM_CACHE=true # Impede que Next.js guarde cache dos arquivos
    # command: sh -c "sleep 2 && rm -rf .next && npm run dev"  # Sempre remove cache antes de rodar

    # com estes removidos, só foi preciso:
    # --- npm install
    # --- npm run dev
